# Keras: The Python Deep Learning library

Keras is a high-level neural networks API, written in Python and capable of running on top of TensorFlow, CNTK, or Theano. It was developed with a focus on enabling fast experimentation. Being able to go from idea to result with the least possible delay is key to doing good research.



In [2]:
import keras
from keras.models import load_model
import tensorflow as tf
import pandas as pd
import numpy as np

c:\users\khatwd2\appdata\local\continuum\anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [3]:
#get the iris data into pandas and clean up the column names into ones compatible with tensorflow
from sklearn import datasets
import pandas as pd
from sklearn.model_selection import train_test_split
import tensorflow as tf
iris = datasets.load_iris()
df = pd.DataFrame(iris.data,columns=iris.feature_names)
df.columns=[colname[:-4].strip().replace(' ','_') for colname in df.columns]
df['target'] = pd.Series(iris.target)
print(df.head())

y=df['target']
#keras requires one-hot encoded output
y=pd.get_dummies(y)
X=df.drop('target',axis=1)
X= np.array(X)
y=np.array(y)
# split the data into trainning and test data sets
X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42)


num_features=X_train.shape[1]

   sepal_length  sepal_width  petal_length  petal_width  target
0           5.1          3.5           1.4          0.2       0
1           4.9          3.0           1.4          0.2       0
2           4.7          3.2           1.3          0.2       0
3           4.6          3.1           1.5          0.2       0
4           5.0          3.6           1.4          0.2       0


## Keras Sequential API

We still simply stack multiple dense layers together to create a neural network.

In [4]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(units=10, activation='relu', input_dim=num_features))
model.add(Dense(units=20, activation='relu'))
model.add(Dense(units=10, activation='relu'))
model.add(Dense(units=3, activation='softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer='sgd',
              metrics=['accuracy'])

#10 epoch isnt enough to obtain a good accuracy
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

#save the model 
model.save('keras_partly_trained.h5')

#load the model
model = load_model('keras_partly_trained.h5')

#keep training where we left off before
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

#get summary of model architecture
model.summary()

Instructions for updating:
keep_dims is deprecated, use keepdims instead
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Train on 120 samples, validate on 30 samples
Epoch 1/10
120/120 [==============================] - 0s 3ms/step - loss: 1.4910 - acc: 0.4000 - val_loss: 1.2765 - val_acc: 0.4667
Epoch 2/10
120/120 [==============================] - 0s 133us/step - loss: 1.2254 - acc: 0.4750 - val_loss: 1.1070 - val_acc: 0.5333
Epoch 3/10
120/120 [==============================] - 0s 142us/step - loss: 1.0751 - acc: 0.5417 - val_loss: 1.0044 - val_acc: 0.6000
Epoch 4/10
120/120 [==============================] - 0s 142us/step - loss: 0.9930 - acc: 0.5333 - val_loss: 0.9461 - val_acc: 0.5667
Epoch 5/10
120/120 [==============================] - 0s 183us/step - loss: 0.9433 - acc: 0.5833 - val_loss: 0.9134 - val_acc: 0.7667
Epoch 6/10
120/120 [==============================] - 0s 150us/step - loss: 0.9150 - acc: 0.8250 - val_loss: 0.8892 - val_acc: 0.9000
Epoch 7

In [5]:
#lets look at the test loss and accuracy 
# should match up with the output above
loss_and_metrics = model.evaluate(X_test, y_test, batch_size=128)
print(loss_and_metrics)

classes = model.predict(X_test, batch_size=128)
print(classes)

#get the index of the max probability for each row to get the predicted class
classes.argmax(1)

30/30 [==============================] - 0s 167us/step
[0.583909809589386, 0.8333333134651184]
[[0.0889056  0.571777   0.33931732]
 [0.7434156  0.14440481 0.11217957]
 [0.03366585 0.4872718  0.47906235]
 [0.12053287 0.5022369  0.37723023]
 [0.09839346 0.6108736  0.29073298]
 [0.7182701  0.15545759 0.12627229]
 [0.21468848 0.47803926 0.3072723 ]
 [0.12131833 0.44295686 0.43572482]
 [0.10065459 0.5804552  0.31889024]
 [0.15961279 0.5422895  0.29809773]
 [0.10350662 0.44218698 0.45430636]
 [0.6542203  0.20061293 0.1451668 ]
 [0.7427429  0.14014848 0.11710869]
 [0.6528448  0.20468748 0.14246772]
 [0.7662282  0.12129451 0.11247732]
 [0.12516148 0.4838999  0.39093855]
 [0.05540251 0.40406165 0.5405358 ]
 [0.14050543 0.55789036 0.30160418]
 [0.10283836 0.51258194 0.38457963]
 [0.06160897 0.41436985 0.5240212 ]
 [0.6397836  0.2059724  0.15424404]
 [0.09998566 0.45028985 0.44972444]
 [0.6972236  0.16639324 0.13638319]
 [0.05963063 0.43112758 0.50924176]
 [0.05157655 0.526573   0.42185038]
 [0.1

array([1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 1,
       0, 2, 1, 2, 1, 2, 0, 0], dtype=int64)

## Keras Functional API

The Keras functional API is the way to go for defining complex models, such as multi-output models, directed acyclic graphs, or models with shared layers.

### Re-implement Feed Forward nework with funcional API
The Sequential model is probably a better choice to implement such a network, but it helps to start with something really simple.

In [6]:
from keras.layers import Input, Dense
from keras.models import Model

# This returns a tensor
inputs = Input(shape=(784,))

# a layer instance is callable on a tensor, and returns a tensor
inputs = Input(shape=(4,))
x = Dense(10,activation='relu')(inputs)
x = Dense(20, activation='relu')(x)
x = Dense(units=10, activation='relu')(x)
predictions = Dense(3, activation='softmax')(x)

# This creates a model that includes
# the Input layer and three hidden Dense layers
model = Model(inputs=inputs, outputs=predictions)
model.compile(optimizer='sgd',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

#10 epoch isnt enough to obtain a good accuracy
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

#save the model 
model.save('keras_partly_trained.h5')

#load the model
model = load_model('keras_partly_trained.h5')

#keep training where we left off before
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

#get summary of model architecture
model.summary()

Train on 120 samples, validate on 30 samples
Epoch 1/10
120/120 [==============================] - 0s 4ms/step - loss: 1.1622 - acc: 0.3750 - val_loss: 0.9403 - val_acc: 0.7000
Epoch 2/10
120/120 [==============================] - 0s 108us/step - loss: 0.9501 - acc: 0.6583 - val_loss: 0.8529 - val_acc: 0.7000
Epoch 3/10
120/120 [==============================] - 0s 142us/step - loss: 0.8776 - acc: 0.6583 - val_loss: 0.8136 - val_acc: 0.7000
Epoch 4/10
120/120 [==============================] - 0s 92us/step - loss: 0.8306 - acc: 0.6583 - val_loss: 0.7883 - val_acc: 0.7000
Epoch 5/10
120/120 [==============================] - 0s 200us/step - loss: 0.8087 - acc: 0.6583 - val_loss: 0.7638 - val_acc: 0.7000
Epoch 6/10
120/120 [==============================] - 0s 192us/step - loss: 0.7982 - acc: 0.6583 - val_loss: 0.7483 - val_acc: 0.7000
Epoch 7/10
120/120 [==============================] - 0s 225us/step - loss: 0.7659 - acc: 0.6583 - val_loss: 0.7269 - val_acc: 0.7000
Epoch 8/10
120/120 [